# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.greeting_label = QtWidgets.QLabel(self.centralwidget)
        self.greeting_label.setGeometry(QtCore.QRect(0, 30, 651, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.greeting_label.setFont(font)
        self.greeting_label.setAlignment(QtCore.Qt.AlignCenter)
        self.greeting_label.setObjectName("greeting_label")
        self.new_mp3_button = QtWidgets.QPushButton(self.centralwidget)
        self.new_mp3_button.setGeometry(QtCore.QRect(30, 130, 231, 26))
        self.new_mp3_button.setObjectName("new_mp3_button")
        self.already = QtWidgets.QLabel(self.centralwidget)
        self.already.setGeometry(QtCore.QRect(280, 130, 291, 21))
        self.already.setObjectName("already")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 230, 601, 261))
        self.listWidget.setObjectName("listWidget")
        self.to_friends = QtWidgets.QPushButton(self.centralwidget)
        self.to_friends.setGeometry(QtCore.QRect(30, 180, 381, 26))
        self.to_friends.setObjectName("to_friends")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVK = QtWidgets.QAction(MainWindow)
        self.actionVK.setObjectName("actionVK")
        self.actionFacebook = QtWidgets.QAction(MainWindow)
        self.actionFacebook.setObjectName("actionFacebook")
        self.actionTwitter = QtWidgets.QAction(MainWindow)
        self.actionTwitter.setObjectName("actionTwitter")
        self.actionWeb = QtWidgets.QAction(MainWindow)
        self.actionWeb.setObjectName("actionWeb")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionVK)
        self.menu.addAction(self.actionFacebook)
        self.menu.addAction(self.actionTwitter)
        self.menu.addAction(self.actionWeb)
        self.menu_2.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.greeting_label.setText(_translate("MainWindow", "Здравствуйте, None!"))
        self.new_mp3_button.setText(_translate("MainWindow", "Загрузить новый MP3 файл"))
        self.already.setText(_translate("MainWindow", "Файл уже присутсвует в Вашей медиатеке"))
        self.to_friends.setText(_translate("MainWindow", "Расскажите о нас друзьям!"))
        self.menu.setTitle(_translate("MainWindow", "Поделиться"))
        self.menu_2.setTitle(_translate("MainWindow", "Справка"))
        self.actionVK.setText(_translate("MainWindow", "ВК"))
        self.actionFacebook.setText(_translate("MainWindow", "Facebook"))
        self.actionTwitter.setText(_translate("MainWindow", "Twitter"))
        self.actionWeb.setText(_translate("MainWindow", "Создать совй веб-сайт"))
        self.actionAbout.setText(_translate("MainWindow", "О нас"))
