# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(376, 347)
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 391, 351))
        self.background.setObjectName("background")
        self.cover = QtWidgets.QLabel(Form)
        self.cover.setGeometry(QtCore.QRect(120, 40, 141, 121))
        self.cover.setAlignment(QtCore.Qt.AlignCenter)
        self.cover.setObjectName("cover")
        self.name = QtWidgets.QLabel(Form)
        self.name.setGeometry(QtCore.QRect(17, 185, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.name.setFont(font)
        self.name.setStyleSheet("color: white")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.artist = QtWidgets.QLabel(Form)
        self.artist.setGeometry(QtCore.QRect(10, 220, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.artist.setFont(font)
        self.artist.setStyleSheet("color: white")
        self.artist.setAlignment(QtCore.Qt.AlignCenter)
        self.artist.setObjectName("artist")
        self.action_button = QtWidgets.QPushButton(Form)
        self.action_button.setGeometry(QtCore.QRect(160, 270, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.action_button.setFont(font)
        self.action_button.setStyleSheet("background-color: green; color: white; border-radius: 10")
        self.action_button.setObjectName("action_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.background.setText(_translate("Form", "TextLabel"))
        self.cover.setText(_translate("Form", "TextLabel"))
        self.name.setText(_translate("Form", "Track_Name"))
        self.artist.setText(_translate("Form", "Artist"))
        self.action_button.setText(_translate("Form", "| |"))
