# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(327, 298)
        self.cover = QtWidgets.QLabel(Form)
        self.cover.setGeometry(QtCore.QRect(100, 20, 141, 131))
        self.cover.setObjectName("cover")
        self.name = QtWidgets.QLabel(Form)
        self.name.setGeometry(QtCore.QRect(30, 180, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.action_button = QtWidgets.QPushButton(Form)
        self.action_button.setGeometry(QtCore.QRect(150, 220, 41, 26))
        self.action_button.setObjectName("action_button")
        self.label = QtWidgets.QLabel(self)
        self.label.setText('Также попробуйте нажать на пробел')
        self.label.adjustSize()
        self.label.move(50, 250)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cover.setText(_translate("Form", "TextLabel"))
        self.name.setText(_translate("Form", "Name of the song"))
        self.action_button.setText(_translate("Form", "||"))
